name: Golang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./cmd/app/main.go

    - name: Test
      run: go test -v ./tests/features

    # - name: Deploy to server
    #   env:
    #     VPS_SSH_KEY: ${{secrets.VPS_SSH_KEY}}
    #     VPS_USERNAME: ${{secrets.VPS_USERNAME}}
    #     VPS_IP: ${{secrets.VPS_IP}}
    #   run : |
    #     echo "$VPS_SSH_KEY" > id_rsa
    #     chmod 600 id_rsa
    #     scp -i id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r . $VPS_USERNAME@$VPS_IP:/book-shop
    #     ssh -i id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $VPS_USERNAME@$VPS_IP 'bash -s' < deploy.sh
